[package]
name = "src"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
error-chain = "0.12.4"
reqwest = "0.12.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.117"
tokio = { version = "1", features = ["full"] }
